### ISSUE TITLE
Xcode build failing: ish/fs/sock.c:4:10: fatal error: 'netinet/tcp_fsm.h' file not found

### ISSUE THREAD

**Issue by rrroyal** [tbodt/ish#622]
When trying to build with Xcode 10.0, build fails with this error:
```
[0/1] Regenerating build files.
The Meson build system
Version: 0.53.0
Source dir: /Users/whatever/Git/ish
Build dir: /Users/whatever/Library/Developer/Xcode/DerivedData/iSH-ekimuutxnornjmcfuvajygbaxcqb/Build/Products/Debug-iphoneos/meson
Build type: cross build
Project name: ish
Project version: undefined
C compiler for the build machine: env -u SDKROOT -u IPHONEOS_DEPLOYMENT_TARGET clang (clang 10.0.0 "Apple LLVM version 10.0.0 (clang-1000.11.45.2)")
C linker for the build machine: env -u SDKROOT -u IPHONEOS_DEPLOYMENT_TARGET clang APPLE ld 409.12
C compiler for the host machine: clang (clang 10.0.0 "Apple LLVM version 10.0.0 (clang-1000.11.45.2)")
C linker for the host machine: clang APPLE ld 409.12
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: aarch64
Host machine cpu: aarch64
Target machine cpu family: aarch64
Target machine cpu: aarch64
Dependency threads found: YES unknown (cached)
Library rt found: NO
Library m found: YES
Program /usr/local/opt/llvm/bin/clang found: YES (/usr/local/opt/llvm/bin/clang)
Program check-cc.sh found: YES (/Users/whatever/Git/ish/vdso/check-cc.sh)
Program tools/staticdefine.sh found: YES (/Users/whatever/Git/ish/tools/staticdefine.sh)
Library sqlite3 found: YES
Library unicorn found: NO
Program tests/e2e/e2e.bash found: YES (/Users/whatever/Git/ish/tests/e2e/e2e.bash)
Build targets in project: 4

Found ninja-1.9.0 at /usr/local/bin/ninja
WARNING: Cross file does not specify strip binary, result will not be stripped.
WARNING: Cross file does not specify strip binary, result will not be stripped.
[1/77] Generating ish-gdb.gdb with a custom command.

(...)

ish/fs/sock.c:4:10: fatal error: 'netinet/tcp_fsm.h' file not found
#include <netinet/tcp_fsm.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
[48/77] Compiling C object 'ish@sta/fs_pipe.c.o'.
[49/77] Compiling C object 'ish@sta/fs_sockrestart.c.o'.
ninja: build stopped: subcommand failed.
Command ExternalBuildToolExecution failed with a nonzero exit code
```

`sock.c` requires `netinet/tcp_fsm.h`, but none is supplied. I tried to add the required files, but this is just a rabbit hole and I'm way too sober to jump in.

**Comment by rrroyal** [comment]
Looks like [this commit](https://github.com/tbodt/ish/commit/66f670854e78616cef587ff192c9fe7b2c4160f0) fucked things up, as Travis is failing on macOS too.

**Comment by tbodt** [comment]
This header exists on mac but not ios. I probably have to copy it into the tree or something.

**Comment by rolandoam** [comment]
had the same issue. fixed by copying the file to `netinet/tcp_fsm.h` at the root project (the file is somewhere in your hdd as part of the macOS SDK)
